---
- name: Using Openstack Cloud collection
  hosts: localhost
  tasks:
    - openstack.cloud.server:
        name: datasci_demo
        state: present
        region_name: us-west-1
        image: CentOS 7 (build 2009)
        flavor_ram: 4096
        boot_from_volume: True
        volume_size: 75
        network: demo-net-1
